### ISSUE TITLE
Can you explain the format of your test data

### ISSUE THREAD

**Issue by wuhongsheng** [jamm1985/seismo-performer#16]

**Comment by Syler1984** [comment]
Hello, the `test/archives` files are **mseed** files. Each of them represents a waveform data channel. These archives are dated April 4, 2021 and contain a verified seismic event at around 12:36:00.

You can check [this section](https://github.com/jamm1985/seismo-performer#how-to-predict-on-archives) or [my reply](https://github.com/jamm1985/seismo-performer/issues/15#issuecomment-1517645892) under you first issue.

If you are asking about training/testing dataset: [here](https://github.com/jamm1985/seismo-performer#train-datasets).

**Comment by wuhongsheng** [comment]
> Hello, the `test/archives` files are **mseed** files. Each of them represents a waveform data channel. These archives are dated April 4, 2021 and contain a verified seismic event at around 12:36:00.
> 
> You can check [this section](https://github.com/jamm1985/seismo-performer#how-to-predict-on-archives) or [my reply](https://github.com/jamm1985/seismo-performer/issues/15#issuecomment-1517645892) under you first issue.
> 
> If you are asking about training/testing dataset: [here](https://github.com/jamm1985/seismo-performer#train-datasets).

I wonder how I can convert my own data into this format

**Comment by Syler1984** [comment]
What is your test data format?
